title: 'HackBU - Binghamton University'
description: 'HackBU is a club at Binghamton University created to foster a community of individuals who solve problems through the innovative use of technology.'
og_site_name: 'HackBU'
og_title: 'HackBU - Spring 2014'
og_image: 'http://hackbu.org/img/hackbu.png'
fb_admins: 1352160452
fb_app_id: 737007022995217
root: 'http://hackbu.org'
safe: true
lsi: false
pygments: true